// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopAPI.Contexts;

#nullable disable

namespace ShopAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240617075157_AddedSeedData")]
    partial class AddedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("ShopAPI.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Soft drinks, coffees, teas, beers, and ales",
                            Name = "Beverages"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Sweet and savory sauces, relishes, spreads, and seasonings",
                            Name = "Condiments"
                        });
                });

            modelBuilder.Entity("ShopAPI.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Description = "10 boxes x 20 bags",
                            Name = "Chai",
                            Price = 10f
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Description = "24 - 12 oz bottles",
                            Name = "Chang",
                            Price = 20f
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 1,
                            Description = "12 - 355 ml cans",
                            Name = "Guaraná Fantástica",
                            Price = 30f
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 1,
                            Description = "24 - 12 oz bottles",
                            Name = "Sasquatch Ale",
                            Price = 40f
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 1,
                            Description = "24 - 12 oz bottles",
                            Name = "Steeleye Stout",
                            Price = 50f
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 2,
                            Description = "12 - 550 ml bottles",
                            Name = "Aniseed Syrup",
                            Price = 60f
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 2,
                            Description = "48 - 6 oz jars",
                            Name = "Chef Anton's Cajun Seasoning",
                            Price = 70f
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 2,
                            Description = "36 boxes",
                            Name = "Chef Anton's Gumbo Mix",
                            Price = 80f
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 2,
                            Description = "12 - 8 oz jars",
                            Name = "Grandma's Boysenberry Spread",
                            Price = 90f
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 2,
                            Description = "12 - 1 lb pkgs.",
                            Name = "Uncle Bob's Organic Dried Pears",
                            Price = 100f
                        });
                });

            modelBuilder.Entity("ShopAPI.Entities.Product", b =>
                {
                    b.HasOne("ShopAPI.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShopAPI.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
